### PR TITLE
Add annotation ability to a choicescript game

### PR DESCRIPTION
**Pull request by Gantron1**
Guided by the belief that story-game beta-testers will be more likely to report bugs, typos, and suggestions if it's made easy for them, I wanted to add Hypothes.is (an annotation system) to choicescript. This pull request adds it. Please let me know if it could be done in a better way, as my understanding of the code is still incomplete.

Usually Hypothes.is can be added to a website by adding a single <script> in the html's head section, but since choicescript uses javascript to generate each page, I had to modify the url (without reloading the page). This is as per Hypothesi.is tech support which gave me the following: https://gist.github.com/seanh/4d42c04a330d813d199db616abaa7fc4

### CODE REVIEW

**Comment by dfabulich** [comment]
I don't currently think I want to merge this, though I could perhaps be talked into it.

1) The current scene and line number are not enough information. You'd also need to record the values of the current stats and temps. That will probably be too much information to fit into an URL.
2) Adding the information to the URL could also be spoilery.
3) I don't think we should add an external third-party script dependency to ChoiceScript; especially compiled CS games should be self-contained HTML files
4) I'm not a huge fan of Hypothesis's UI

There's another hidden feature of ChoiceScript that we could expose more publicly, in `ui.js`, `reportBug()` which pops up a UI for describing what went wrong. It currently then uses `choiceofgames.com` to post the message to our server, which sends it as an email to us. The bug report includes all the stats, temps, line number, etc. we'd need to reproduce the issue, but perhaps it could just fire off a `mailto:` link to notify the game's author of issues.

I'd be more in favor of making a "report bug" button visible on the screen that activates `reportBug()`, rather than integrating Hypothesis.

**Comment by Gantron1** [comment]
What I was thinking was that there could be a separate branch for a beta-tester version of choicescript which has features, including Hypothes.is, that shouldn't be in the main branch. 

What you're describing in terms of reportBug() and stats and temps fitting in the url, is a bit of a different use-case than what I was envisioning using Hypothes.is for. My use-case is more for reporting typos, story arc ideas, and other things more about _writing_, as opposed to bug reporting. A dialogue could ensue, which currently has to happen via forum posts, but it'd be nice if it were connected to the respective game pages themselves. 

However, now that you mention it, having full stats and temps values would be nice to have. Incidentally, using the url's querystring is only to get Hypothesis to work, not to convey information back to the writer. If I could have made Hypothesis work without that, I would have. I'll think about ways I could send that information using Hypothesis.

Now you've got me wondering if a "report bug" button would be better. Hmm... Well, the main downside, IMO, is that it makes the dialogue aspect more difficult, but perhaps not onerously so? What if I made it so the writer could choose which method (or both) they want to have in their WiP version of their story? This way we could see what real authors and beta-testers like in the field and change the WiP version accordingly.

I'm currently working on other WiP-only features that I want when writing my stories, and I've made it so that there's a new command, *debug. If you put "*debug annotator" in the startup.txt scene, it turns Hypothesis on. Otherwise, it's off. Another parameter to *debug turns on or off the hidden debug feature of yours (that shows the stats on each game page). "*debug jumper" turns on a feature that lets the user call a *goto_scene by inputing GET parameters in the url. It saves time when writing a game to be able to jump easily to anywhere in the story. It'd also be nice to let a beta-tester modify stats in-game.

I have other WiP features planned too, but my point is that I could add another *debug parameter to let people turn on the reportBug() feature.

One final question, which I hope is not too off-topic, but when I am debugging a story I'm writing and put a *goto_scene (that jumps to a *label) at the beginning of startup.txt, it often skips past my *temp declarations, causing an error. I've figured out a way around this, but what would be wrong with collecting all *temp vars when the scene is initially loaded, allowing them to be referenced before their declaration in the code? This would seem to fix the general problem of undefined *temp vars when using *goto_scene with a *label, not just when debugging a story.

For now, I'm just making the collecting of *temp vars part of my "jumper" feature, but shouldn't it work like that all the time?

**Comment by dfabulich** [comment]
It does kinda sound like `reportBug` is the wrong name for this; I agree that people can and should push the button for any reason whatsoever.

I have thought about "hosting" `*temp` declarations, either automatically, or by requiring `*temp` to appear at the top of the file, but it could introduce weird bugs, so I haven't taken time to focus on it.

**Comment by dfabulich** [comment]
I think this conversation is wrapped up?

**Pull request closed without merging**
